package com.example.mikael.quaestiofix;

import android.os.Bundle;
import android.support.v7.app.AppCompatActivity;
import android.view.View;
import android.widget.Button;
import android.widget.TextView;

import java.util.ArrayList;

/**
 * Created by mikae on 3/28/2016.
 */
public class SoloGameActivity extends AppCompatActivity{
    private int count = 0;
    private int points = 0;
    private int score = 0;
    private String difficultyString;
    public String answerValue;
    protected void onCreate(Bundle savedInstanceState){
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_solo);
        quiz("a0");
        final Button ans1 = (Button) findViewById(R.id.btnans1);
        final Button ans2 = (Button) findViewById(R.id.btnans2);
        final Button ans3 = (Button) findViewById(R.id.btnans3);
        final Button ans4 = (Button) findViewById(R.id.btnans4);
        ans1.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                String btnText=ans1.getText().toString();
                quiz(btnText);
            }
        });
        ans2.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {

                String btnText=ans2.getText().toString();
                quiz(btnText);
            }
        });
        ans3.setOnClickListener(new View.OnClickListener(){
            @Override
            public void onClick (View v){

                String btnText=ans3.getText().toString();
                quiz(btnText);
            }
        });
        ans4.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {

                String btnText=ans4.getText().toString();
                quiz(btnText);
            }
        });
    }


    private void quiz(String chosenAnswer){
        TextView question =(TextView) findViewById(R.id.lblquestion);
        TextView newScore = (TextView) findViewById(R.id.lblscores);
        TextView difficulty = (TextView) findViewById(R.id.lbldifficulty);
        Button answer1 = (Button)findViewById(R.id.btnans1);
        Button answer2 = (Button)findViewById(R.id.btnans2);
        Button answer3 = (Button)findViewById(R.id.btnans3);
        Button answer4=(Button)findViewById(R.id.btnans4);
//Trivia list
        ArrayList<String> trivia = new ArrayList<>();
        trivia.add( "How many hydrogen atoms are in one molecule of water?");
        trivia.add( "Hard");
        trivia.add( "Two");
        trivia.add("One");
        trivia.add("Eight");
        trivia.add("Two");
        trivia.add("Five");
        trivia.add( "Orson Welles provided the voice for which Transformer in the movie The Transformers: the Movie released in 1986?");
        trivia.add( "Very Hard");
        trivia.add( "Unicron");
        trivia.add("Megatron");
        trivia.add("Bumblebee");
        trivia.add("Metatron");
        trivia.add("Unicron");
        trivia.add( "Which US President was known as The Great Communicator?");
        trivia.add( "Easy");
        trivia.add( "Ronald Regan");
        trivia.add("Ronald Regan");
        trivia.add("John F. Kennedy");
        trivia.add("Franklin Roosevelt");
        trivia.add("Dwight D. Eisenhauer");
        trivia.add( "What is a traditional fermented Korean side dish made with seasoned vegetables and salt?");
        trivia.add( "Very Hard");
        trivia.add( "Kimchi");
        trivia.add("Aichi");
        trivia.add("Saki");
        trivia.add("Palito");
        trivia.add("Kimchi");
        trivia.add( "Catalonia is a region of what country?");
        trivia.add( "Very Hard");
        trivia.add( "Spain");
        trivia.add("Germany");
        trivia.add("France");
        trivia.add("Spain");
        trivia.add("Italy");
        trivia.add( "CERN launched the very first website in what year?");
        trivia.add( "Medium");
        trivia.add( "1990");
        trivia.add("1988");
        trivia.add("1992");
        trivia.add("1953");
        trivia.add("1987");
        trivia.add( "What was the name of Robert E. Lee's most famous horse?");
        trivia.add( "Very Hard");
        trivia.add( "Traveller");
        trivia.add("Magician");
        trivia.add("Apocalyptica");
        trivia.add("Slaver");
        trivia.add("Traveller");
        trivia.add( "Who played Dracula in the 1931 vampire-horror film Dracula?");
        trivia.add( "Medium");
        trivia.add( "Bela Lugosi");
        trivia.add("Vlad Impala");
        trivia.add("Bradley Pitt");
        trivia.add("Sean Eichorst");
        trivia.add("Bela Lugosi");
        trivia.add( "In which US state would you find Stone Mountain Park?");
        trivia.add( "Medium");
        trivia.add( "Georgia");
        trivia.add("Minnesota");
        trivia.add("Nebraska");
        trivia.add("Georgia");
        trivia.add("North Carolina");
        trivia.add( "A teetotaler is a person that never drinks what?");
        trivia.add( "Easy");
        trivia.add( "Alcohol");
        trivia.add("Tea");
        trivia.add("Soda/Pop");
        trivia.add("Water");
        trivia.add("Alcohol");
        trivia.add( "Who was the first human to travel into space?");
        trivia.add( "Hard");
        trivia.add( "Yuri Gagarin");
        trivia.add("Neal Armstrong");
        trivia.add("Yuri Gagarin") ;
        trivia.add("Buzz Aldrin");
        trivia.add("Ron White");
        trivia.add( "A tandoor is a type of what?");
        trivia.add( "Easy");
        trivia.add( "Oven");
        trivia.add("Oven");
        trivia.add("Microwave");
        trivia.add("Lock");
        trivia.add("Cupboard");
        trivia.add( "A puggle is a cross between which two dog breeds?");
        trivia.add( "Easy");
        trivia.add( "Pug and Beagle");
        trivia.add("Poodle and Pug");
        trivia.add("Pug and Beagle");
        trivia.add("German Shephard and Rottweiler");
        trivia.add("Chihuahua and Poodle");
        trivia.add( "The Roman numeral D stands for what number?");
        trivia.add( "Easy");
        trivia.add( "500");
        trivia.add("200");
        trivia.add("250");
        trivia.add("300");
        trivia.add("500");
        trivia.add( "How do you say Hello in German?");
        trivia.add( "Easy");
        trivia.add( "Hallo");
        trivia.add("Hello");
        trivia.add("Hallo");
        trivia.add("Hola");
        trivia.add("Ich Lieben");
        trivia.add( "Malcolm Little was a civil rights activist better known by what name?");
        trivia.add( "Medium");
        trivia.add( "Malcolm X");
        trivia.add("Muhammad Ali");
        trivia.add("Malcolm X");
        trivia.add("Mack Salizar");
        trivia.add("Martin Luther King, Jr.");
        trivia.add( "How many states are needed to raitfy an amendment for it to become part of the constitution?");
        trivia.add( "Hard");
        trivia.add( "3/4 of the states, or 38/50");
        trivia.add("1/2 of the states, or 25/50");
        trivia.add("1/10 of the states, or 5/50");
        trivia.add("All of the states, or 50/50");
        trivia.add("None, it's an executive decision held by the President");
        trivia.add( "What is the name of Washington Irving's 1819 shrot story about a man that fell asleep in the woods for 20 years?");
        trivia.add( "Medium");
        trivia.add( "Rip Van Winkle");
        trivia.add("Rip Van Winkle");
        trivia.add("Dick Van Dyke");
        trivia.add("Man of the Woods");
        trivia.add("Chronicles of Narnia");
        trivia.add( "What is the name for the Greek Goddess of victory?");
        trivia.add( "Easy");
        trivia.add( "Nike");
        trivia.add("Aphrodite");
        trivia.add("Athena");
        trivia.add("Nike");
        trivia.add("Nemesis");
        trivia.add( "Who was the female lead in the movie, Titanic?");
        trivia.add( "Easy");
        trivia.add( "Kate Winslet");
        trivia.add("Katherine Zeta Jones");
        trivia.add("Mila Kunis");
        trivia.add("Adele");
        trivia.add("Kate Winslet");
        trivia.add( "Who plays the role of Dean Winchester in the popular TV show, Supernatural?");
        trivia.add( "Easy");
        trivia.add( "Jensen Ackles");
        trivia.add("Jared Padalecki");
        trivia.add("Jensen Ackles");
        trivia.add("Phil Harmonn");
        trivia.add("Bob Singer");
        trivia.add( "Who is the developer of Quaestio?");
        trivia.add( "Medium");
        trivia.add( "Mikael Taylor");
        trivia.add("Mark Hammond");
        trivia.add("Bill Gates");
        trivia.add("Steve Wozniak");
        trivia.add("Mikael Taylor");
        trivia.add( "In the popular programming language C#, which of the following would write text to a text file?");
        trivia.add( "Medium");
        trivia.add( "StreamWriter");
        trivia.add("StreamWriter");
        trivia.add("Textbox");
        trivia.add("c#textFilter");
        trivia.add("ScriptEditor");
        trivia.add( "Which man is the leader of Woodbury in the hit TV show, the Walking Dead?");
        trivia.add( "Medium");
        trivia.add( "The Governor, Philip Blake");
        trivia.add("The Terminator, Arnold");
        trivia.add("Rick Grimes");
        trivia.add("Shane Walsh");
        trivia.add("The Governor, Philip Blake");
        trivia.add( "What was the Black Pearl named before it was known as the Black Pearl, in the Pirates of the Caribbean movie series?");
        trivia.add( "Medium");
        trivia.add( "The Wicked Wench");
        trivia.add("White Whaters");
        trivia.add("Painted Pigeon");
        trivia.add("The Wicked Wench");
        trivia.add("Burley Burgeoness");
        trivia.add( "In the hit comic series, the Walking Dead, who was the original leader of the Hilltop Community?");
        trivia.add( "Easy");
        trivia.add( "Gregory");
        trivia.add("Mallory");
        trivia.add("Gregory");
        trivia.add("Phil");
        trivia.add("Jesus");
        trivia.add( "Who was the first president of the United States");
        trivia.add( "Very Easy");
        trivia.add( "George Washington");
        trivia.add("George Carver");
        trivia.add("George Washington");
        trivia.add("Theodore Roosevelt");
        trivia.add("Rand Paul");
        trivia.add( "What does the Jolly Roger flag traditionally represent?");
        trivia.add( "Very Easy");
        trivia.add( "Piracy");
        trivia.add("Freedom");
        trivia.add("Information Security");
        trivia.add("Sailors");
        trivia.add("Piracy");
        trivia.add( "In the massively multiplayer space sandbox game, Eve Online, which coalition did the Mittani belong to at the beginning of the Great War of 2016?");
        trivia.add( "Hard");
        trivia.add( "The Imperium");
        trivia.add("The Corp Coalition");
        trivia.add("Pandemic Legion");
        trivia.add("Karmafleet");
        trivia.add("The Imperium");
        trivia.add( "At the beginning of the Cataclysm Expansion in the hit MMO, 'World of Warcraft' who was the leader of the Horde?");
        trivia.add( "Medium");
        trivia.add( "Thrall");
        trivia.add("Durotan");
        trivia.add("Thrall");
        trivia.add("Grommash Hellscream");
        trivia.add("Deathwing");
        trivia.add( "What were the Aztec's group of elite warriors called during the Spanish attack led by  Cortez?");
        trivia.add( "Very Hard");
        trivia.add( "The Eagles");
        trivia.add("The Eagles");
        trivia.add("Quetzalcoatlus");
        trivia.add("The Phantoms");
        trivia.add("Aztec SpecOps");
        trivia.add( "In what year did the Apollo 7 spaceflight take place?");
        trivia.add( "Medium");
        trivia.add( "1968");
        trivia.add("1967");
        trivia.add("1968");
        trivia.add("1969");
        trivia.add("1970");
        trivia.add( "What day is Thanksgiving celebrated in Canada?");
        trivia.add( "Hard");
        trivia.add( "The second monday of October");
        trivia.add("The third thursday of November");
        trivia.add("The first monday of October");
        trivia.add("the second monday of October");
        trivia.add("The third monday of October");
        trivia.add( "Sodium chloride is most commonly known as what?");
        trivia.add( "Medium");
        trivia.add( "Salt");
        trivia.add("Pepper");
        trivia.add("Salt");
        trivia.add("Ice");
        trivia.add("Iron");
        trivia.add( "Which animal has the longest gestation period?");
        trivia.add( "Very Easy");
        trivia.add( "Elephants");
        trivia.add("Elephants");
        trivia.add("Whales");
        trivia.add("Humans");
        trivia.add("Apes");
        trivia.add( "Kinnikinnick is a Native American herbal mixture used as a substitute for what?");
        trivia.add( "Hard");
        trivia.add( "Tobacco");
        trivia.add("Glue");
        trivia.add("Tobacco");
        trivia.add("Bleach");
        trivia.add("Gasoline");
        trivia.add( "The use of reflected sounds to locate objects is known as what?");
        trivia.add( "Very Easy");
        trivia.add( "Echolocation");
        trivia.add("Reverberation");
        trivia.add("Sonic Boom");
        trivia.add("Echolocation");
        trivia.add("Heart Murmur");
        trivia.add( "The Southern Ocean surrounds which continent?");
        trivia.add( "Medium");
        trivia.add( "Antarctica");
        trivia.add("Antarctica");
        trivia.add("Australia");
        trivia.add("South America");
        trivia.add("Africa");
        trivia.add( "The Statue of Liberty was given as a gift to the United States from which country?");
        trivia.add( "Easy");
        trivia.add( "France");
        trivia.add("Spain");
        trivia.add("Portugal");
        trivia.add("France");
        trivia.add("Germany");
        trivia.add( "Kopi luwak is a very expensive type of what?");
        trivia.add( "Hard");
        trivia.add( "Coffee");
        trivia.add("Liquor");
        trivia.add("Coffee");
        trivia.add("Soda/Pop");
        trivia.add("Laxative");
        trivia.add( "Who wrote the 1936 novel 'Gone with the Wind'?");
        trivia.add( "Very Easy");
        trivia.add( "Margaret Mitchell");
        trivia.add("Margaret Mitchell");
        trivia.add("Margot Landall");
        trivia.add("Michelle Marjory");
        trivia.add("Mark Sheppard");
        trivia.add( "The Arabian Camel, also called dromedary, has how many humps?");
        trivia.add( "Easy");
        trivia.add( "1");
        trivia.add("3");
        trivia.add("2");
        trivia.add("1");
        trivia.add("1.5");
        trivia.add( "In what month is the longest day in the Northern Hemisphere?");
        trivia.add( "Medium");
        trivia.add( "June");
        trivia.add("July");
        trivia.add("August");
        trivia.add("June");
        trivia.add("April");
        trivia.add( "What is the fear of clowns called?");
        trivia.add( "Hard");
        trivia.add( "Coulrophobia");
        trivia.add("Arachniphobia");
        trivia.add("Comicophobia");
        trivia.add("Coulrophobia");
        trivia.add("Agoraphobia");
        trivia.add( "In the Greek pantheon, which God represented the Sea?");
        trivia.add( "Easy");
        trivia.add( "Poseidon");
        trivia.add("Persephone");
        trivia.add("Aphrodite");
        trivia.add("Poseidon");
        trivia.add("Perseus");
        trivia.add( "In the world of video games, what does NES stand for?");
        trivia.add( "Easy");
        trivia.add( "Nintendo Entertainment System");
        trivia.add("Not Especially Sporty");
        trivia.add("New Entertainment System");
        trivia.add("Nintendo Entertainment System");
        trivia.add("Northern European Sega");
        trivia.add( "Robert James Bobby Fischer is a famous champion of what game?");
        trivia.add( "Very Hard");
        trivia.add( "Chess");
        trivia.add("Checkers");
        trivia.add("Monopoly");
        trivia.add("Chess");
        trivia.add("Backgammon");
        trivia.add( "What is the world's largest active volcano?");
        trivia.add( "Medium");
        trivia.add( "Mauna Loa(Hawaii)");
        trivia.add("Mt. St. Helen(Washington)");
        trivia.add("Big Lava {Texas}");
        trivia.add("Mauna Loa(Hawaii)");
        trivia.add("Maui Rouge{Hawaii}");
        trivia.add( "What is the word for Hello in Spanish?");
        trivia.add( "Easy");
        trivia.add( "Hola");
        trivia.add("Hello");
        trivia.add("Hola");
        trivia.add("Hallo");
        trivia.add("Hulga");
        trivia.add( "Who is the current Supreme Leader of North Korea?");
        trivia.add( "Hard");
        trivia.add( "Kim Jong Un");
        trivia.add("Kim Jong Il");
        trivia.add("Kim Jong Un");
        trivia.add("Maori Tisdale");
        trivia.add("Jimmy Fallon");
        trivia.add( "Which actor that once played James Bond previously competed in the Mr. Universe bodybuilding competition?");
        trivia.add( "Very Easy");
        trivia.add( "Sean Connery");
        trivia.add("Sean Connery");
        trivia.add("John McCain");
        trivia.add("Kim Jong Un");
        trivia.add("Frank Sinatra");
        if(count == 0){
            difficultyString=trivia.get(count+1);
            question.setText(trivia.get(count));
            answer1.setText(trivia.get(count+3));
            answer2.setText(trivia.get(count+4));
            answer3.setText(trivia.get(count+5));
            answer4.setText(trivia.get(count+6));
            difficulty.setText(difficultyString);
            answerValue=trivia.get(count+2);
            score= score+points;
            String updateScore= String.valueOf(score);
            newScore.setText(updateScore);
            count++;
        }else if(count <= 50 && count > 0){
            int stringCount=count*7;
            difficultyString=trivia.get(stringCount+1);
            question.setText(trivia.get(stringCount));
            answer1.setText(trivia.get(stringCount+3));
            answer2.setText(trivia.get(stringCount+4));
            answer3.setText(trivia.get(stringCount+5));
            answer4.setText(trivia.get(stringCount+6));
            difficulty.setText(difficultyString);

            if(answerValue.equals(chosenAnswer)) {
                points = 100;
                score = score + points;
            }
            String scoreString = String.valueOf(score);
            newScore.setText(scoreString);
            answerValue=trivia.get(stringCount+2);
            count++;
        } else if(count>50){
                String doneText="ALL DONE! YAAAY! Your score was "+score+"!";
                question.setText(doneText);
            Button btn1 = (Button) findViewById(R.id.btnans1);
            btn1.setVisibility(View.GONE);
            Button btn2 = (Button) findViewById(R.id.btnans2);
            btn2.setVisibility(View.GONE);
            Button btn3 = (Button) findViewById(R.id.btnans3);
            btn3.setVisibility(View.GONE);
            Button btn4 = (Button) findViewById(R.id.btnans4);
            btn4.setVisibility(View.GONE);
            }
        }

}
